version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: composer
  directory: "/_backend"
  schedule:
    interval: weekly
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
