- has_config: false
  name: .github
  updates: []
- has_config: true
  name: .normal
  updates:
  - all_dependencies: false
    directory: /
    interval: daily
    package_ecosystem: github-actions
    supports_all: false
    target_branch: main
- has_config: true
  name: .releases
  updates:
  - all_dependencies: false
    directory: /
    interval: monthly
    package_ecosystem: github-actions
    supports_all: false
    target_branch: main
- has_config: true
  name: .ui
  updates:
  - all_dependencies: false
    directory: /
    interval: weekly
    package_ecosystem: github-actions
    supports_all: false
    target_branch: main
  - all_dependencies: true
    directory: /
    interval: weekly
    package_ecosystem: npm
    supports_all: true
    target_branch: main
- has_config: false
  name: .uptime
  updates: []
- has_config: true
  name: Bubbly
  updates:
  - all_dependencies: false
    directory: /
    interval: monthly
    package_ecosystem: github-actions
    supports_all: false
    target_branch: main
- has_config: true
  name: Colors.css
  updates:
  - all_dependencies: false
    directory: /
    interval: monthly
    package_ecosystem: github-actions
    supports_all: false
    target_branch: main
- has_config: true
  name: Locksmith
  updates:
  - all_dependencies: false
    directory: /
    interval: weekly
    package_ecosystem: github-actions
    supports_all: false
    target_branch: main
  - all_dependencies: true
    directory: /
    interval: weekly
    package_ecosystem: pip
    supports_all: true
    target_branch: main
- has_config: true
  name: Phoenix
  updates:
  - all_dependencies: true
    directory: /
    interval: monthly
    package_ecosystem: composer
    supports_all: true
    target_branch: 3.x
  - all_dependencies: true
    directory: /
    interval: weekly
    package_ecosystem: composer
    supports_all: true
    target_branch: main
  - all_dependencies: false
    directory: /
    interval: monthly
    package_ecosystem: github-actions
    supports_all: false
    target_branch: 3.x
  - all_dependencies: false
    directory: /
    interval: weekly
    package_ecosystem: github-actions
    supports_all: false
    target_branch: main
- has_config: true
  name: apple-silicon
  updates:
  - all_dependencies: false
    directory: /
    interval: weekly
    package_ecosystem: github-actions
    supports_all: false
    target_branch: main
  - all_dependencies: true
    directory: /
    interval: weekly
    package_ecosystem: npm
    supports_all: true
    target_branch: main
- has_config: true
  name: authenticatron
  updates:
  - all_dependencies: true
    directory: /
    interval: monthly
    package_ecosystem: composer
    supports_all: true
    target_branch: main
  - all_dependencies: false
    directory: /
    interval: monthly
    package_ecosystem: github-actions
    supports_all: false
    target_branch: main
- has_config: true
  name: browning
  updates:
  - all_dependencies: true
    directory: /
    interval: monthly
    package_ecosystem: composer
    supports_all: true
    target_branch: main
  - all_dependencies: false
    directory: /
    interval: monthly
    package_ecosystem: github-actions
    supports_all: false
    target_branch: main
- has_config: false
  name: elementary-bluetooth-proximity-locker
  updates: []
- has_config: true
  name: eustasy.org
  updates:
  - all_dependencies: true
    directory: /
    interval: monthly
    package_ecosystem: bun
    supports_all: true
    target_branch: cf-pages
  - all_dependencies: false
    directory: /
    interval: monthly
    package_ecosystem: github-actions
    supports_all: false
    target_branch: cf-pages
- has_config: false
  name: howtoubuntu.org
  updates: []
- has_config: false
  name: jQuery.leanModal2
  updates: []
- has_config: false
  name: puff-server
  updates: []
- has_config: true
  name: puff-serverless
  updates:
  - all_dependencies: false
    directory: /
    interval: weekly
    package_ecosystem: github-actions
    supports_all: false
    target_branch: cf-pages
  - all_dependencies: true
    directory: /
    interval: weekly
    package_ecosystem: npm
    supports_all: true
    target_branch: cf-pages
